
name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true



      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn
      
      - name: Enable Corepack
        run: corepack enable  # 启用 Corepack

      - name: Verify Corepack and Yarn Version
        run: |
          corepack --version  # 确保 Corepack 已启用
          yarn --version  # 检查正在使用的 Yarn 版本

      - name: Install dependencies with Corepack
        run: yarn install  # 使用 Corepack 管理的 yarn 安装依赖

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          yarn run docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: docs/.vuepress/dist
