
name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true



      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Uninstall global Yarn
        run: |
          sudo npm uninstall -g yarn  # 卸载全局的 Yarn

      - name: Enable Corepack and install Yarn 3.x
        run: |
          corepack enable  # 启用 Corepack
          corepack prepare yarn@3.6.3 --activate  # 激活指定版本的 Yarn
          yarn --version  # 输出当前 Yarn 版本，确保是 3.6.3

      - name: Install dependencies using Yarn
        run: yarn install  # 使用正确版本的 Yarn 安装依赖

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          yarn run docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: docs/.vuepress/dist
